export const puzzleImages = [
  { id: 1, img: './img/1.jpg' },
  { id: 2, img: './img/2.jpg' },
  { id: 3, img: './img/3.jpg' },
  { id: 4, img: './img/4.jpg' },
  { id: 5, img: './img/5.jpg' },
  { id: 6, img: './img/6.jpg' },
  { id: 7, img: './img/7.jpg' },
  { id: 8, img: './img/8.jpg' },
  { id: 9, img: './img/9.jpg' },
  { id: 10, img: './img/10.jpg' },
  { id: 11, img: './img/11.jpg' },
  { id: 12, img: './img/12.jpg' },
  { id: 13, img: './img/13.jpg' },
  { id: 14, img: './img/14.jpg' },
  { id: 15, img: './img/15.jpg' },
  { id: 16, img: './img/16.jpg' },
  { id: 17, img: './img/17.jpg' },
  { id: 18, img: './img/18.jpg' },
  { id: 19, img: './img/19.jpg' },
  { id: 20, img: './img/20.jpg' },
  { id: 21, img: './img/21.jpg' },
  { id: 22, img: './img/22.jpg' },
  { id: 23, img: './img/23.jpg' },
  { id: 24, img: './img/24.jpg' },
  { id: 25, img: './img/25.jpg' },
]
